backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posty"
    label: "Moje Teksty"
    file: "posts.json"
    extension: "json"
    format: "json"
    fields:
      - label: "Wszystkie Posty"
        name: "posts"
        widget: "list"
        fields:
          - {label: "ID (np. tekst-1)", name: "id", widget: "string"}
          - {label: "Tytuł", name: "title", widget: "string"}
          - {label: "Kategoria", name: "category", widget: "select", options: ["Kryminał", "Romans", "Horror"]}
          - {label: "Krótki opis", name: "excerpt", widget: "text"}
          - {label: "Pełna treść", name: "content", widget: "markdown"}
