backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Moje Teksty"
    folder: "teksty"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Opis", name: "excerpt", widget: "text"}
      - {label: "Treść", name: "body", widget: "markdown"}
